-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 23:50:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agencia` DEFAULT CHARACTER SET utf8 ;
USE `agencia` ;

-- -----------------------------------------------------
-- Table `agencia`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `RolNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Roles_idRoles` INT NOT NULL,
  `UsuNombres` VARCHAR(100) NOT NULL,
  `UsuApellidos` VARCHAR(100) NOT NULL,
  `UsuSexo` VARCHAR(1) NOT NULL,
  `UsuUser` VARCHAR(20) NOT NULL,
  `UsuPass` VARCHAR(100) NOT NULL,
  `UsuTelefono` INT NOT NULL,
  `UsuLastSession` DATETIME NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Roles_idx` (`Roles_idRoles` ASC),
  CONSTRAINT `fk_Usuarios_Roles`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `agencia`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `agencia`.`Seguimiento_Bd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`Seguimiento_Bd` (
  `idSeguimiento_Bd` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NULL,
  `SegSentencia` TEXT NOT NULL,
  `SegFechaEje` DATETIME NOT NULL,
  PRIMARY KEY (`idSeguimiento_Bd`),
  INDEX `fk_Seguimiento_Bd_Usuarios1_idx` (`Usuarios_idUsuarios` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `PaisNombre` VARCHAR(45) NOT NULL,
  `PaisSimMon` VARCHAR(45) NOT NULL,
  `PaisCodMon` VARCHAR(45) NOT NULL,
  `PaisFoto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`Ciudad` (
  `Pais_idPais` INT NOT NULL,
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `CiuNombre` VARCHAR(45) NOT NULL,
  `CiuCoord` VARCHAR(45) NOT NULL,
  `CiudadFoto` VARCHAR(100) NULL,
  `CiudDes` TEXT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_Ciudad_Pais1_idx` (`Pais_idPais` ASC),
  CONSTRAINT `fk_Ciudad_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `agencia`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `agencia`.`presupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`presupuesto` (
  `idPresupuesto` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  `PreValorLocal` FLOAT NOT NULL,
  `PreValorPaisSelect` FLOAT NOT NULL,
  `PreValorAlem` FLOAT NOT NULL,
  `PreEstado` INT NOT NULL DEFAULT 0 privado-1Publico,
  PRIMARY KEY (`idPresupuesto`),
  INDEX `fk_presupuesto_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_presupuesto_Ciudad1_idx` (`Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_presupuesto_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `agencia`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presupuesto_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `agencia`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`PermisosCompartir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`PermisosCompartir` (
  `idPermisos` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `presupuesto_idPresupuesto` INT NOT NULL,
  PRIMARY KEY (`idPermisos`),
  INDEX `fk_PermisosCompartir_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_PermisosCompartir_presupuesto1_idx` (`presupuesto_idPresupuesto` ASC) VISIBLE,
  CONSTRAINT `fk_PermisosCompartir_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `agencia`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PermisosCompartir_presupuesto1`
    FOREIGN KEY (`presupuesto_idPresupuesto`)
    REFERENCES `agencia`.`presupuesto` (`idPresupuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
