-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 23:13:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Set session variables
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Create schema if not exists and use it
CREATE SCHEMA IF NOT EXISTS `Agencia` DEFAULT CHARACTER SET utf8 ;
USE `Agencia`;

-- Table: Roles
CREATE TABLE IF NOT EXISTS `Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `RolNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoles`)
) ENGINE = InnoDB;

-- Table: Usuarios
CREATE TABLE IF NOT EXISTS `Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Roles_idRoles` INT NOT NULL,
  `UsuNombres` VARCHAR(100) NOT NULL,
  `UsuApellidos` VARCHAR(100) NOT NULL,
  `UsuSexo` VARCHAR(1) NOT NULL,
  `UsuUser` VARCHAR(20) NOT NULL,
  `UsuPass` VARCHAR(20) NOT NULL,
  `UsuTelefono` INT NOT NULL,
  `UsuLastSession` DATETIME NOT NULL,
  PRIMARY KEY (`idUsuarios`, `Roles_idRoles`),
  INDEX `fk_Usuarios_Roles_idx` (`Roles_idRoles`),
  CONSTRAINT `fk_Usuarios_Roles`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Table: Seguimiento_Bd
CREATE TABLE IF NOT EXISTS `Seguimiento_Bd` (
  `idSeguimiento_Bd` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NULL,
  `SegSentencia` TEXT NOT NULL,
  `SegFechaEje` DATETIME NOT NULL,
  PRIMARY KEY (`idSeguimiento_Bd`),
  INDEX `fk_Seguimiento_Bd_Usuarios1_idx` (`Usuarios_idUsuarios`),
  CONSTRAINT `fk_Seguimiento_Bd_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Table: Pais
CREATE TABLE IF NOT EXISTS `Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `PaisNombre` VARCHAR(45) NOT NULL,
  `PaisSimMon` VARCHAR(45) NOT NULL,
  `PaisCodMon` VARCHAR(45) NOT NULL,
  `PaisFoto` VARCHAR(100) NOT NULL,

  PRIMARY KEY (`idPais`)
) ENGINE = InnoDB;

-- Table: Ciudad
CREATE TABLE IF NOT EXISTS `Ciudad` (
  `Pais_idPais` INT NOT NULL,
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `CiuNombre` VARCHAR(45) NOT NULL,
  `CiuCoord` VARCHAR(45) NOT NULL,
  `CiuFoto` VARCHAR(100) NOT NULL,

  PRIMARY KEY (`idCiudad`), -- Include idCiudad in the primary key
  INDEX `fk_Ciudad_Pais1_idx` (`Pais_idPais`),
  CONSTRAINT `fk_Ciudad_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Table: presupuesto
CREATE TABLE IF NOT EXISTS `presupuesto` (
  `idPresupuesto` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  `PreValorLocal` FLOAT NOT NULL,
  `PreValorPaisSelect` FLOAT NOT NULL,
  `PreValorAlem` FLOAT NOT NULL,
  `PreEstado` INT NOT NULL DEFAULT 0 COMMENT '0: Private, 1: Public',
  PRIMARY KEY (`idPresupuesto`, `Usuarios_idUsuarios`, `Ciudad_idCiudad`),
  INDEX `fk_Usuarios_has_Ciudad_Ciudad1_idx` (`Ciudad_idCiudad`),
  INDEX `fk_Usuarios_has_Ciudad_Usuarios1_idx` (`Usuarios_idUsuarios`),
  CONSTRAINT `fk_Usuarios_has_Ciudad_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Ciudad_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Table: PermisosCompartir
CREATE TABLE IF NOT EXISTS `PermisosCompartir` (
  `idPermisos` INT NOT NULL,
  `presupuesto_idPresupuesto` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idPermisos`, `presupuesto_idPresupuesto`, `Usuarios_idUsuarios`),
  INDEX `fk_presupuesto_has_Usuarios_Usuarios1_idx` (`Usuarios_idUsuarios`),
  INDEX `fk_presupuesto_has_Usuarios_presupuesto1_idx` (`presupuesto_idPresupuesto`),
  CONSTRAINT `fk_presupuesto_has_Usuarios_presupuesto1`
    FOREIGN KEY (`presupuesto_idPresupuesto`)
    REFERENCES `presupuesto` (`idPresupuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presupuesto_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Reset session variables
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
